---
title: "The Botanical Plotter"
author: "Amy Baldwin"
date: "17/03/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r set-up, include=FALSE}
library(tidyverse)
library(ggrepel)

plot_1 <- 
  readr::read_csv("plot_1_location.csv")

```

## Plot number 1

```{r pressure, echo=FALSE}
ggplot(plot_1) +
  aes(x, y) +
   geom_point(
    colour = "darkgreen",
    fill = "green4",
    shape = 24,
    stroke = 1,
    alpha = 0.5
  ) +
  geom_text_repel(
    aes(label = tree_ID),
    fontface = "bold",
    nudge_x = 1,
    nudge_y = 0,
    size = 2
  ) +
  scale_y_continuous(
    breaks = seq(0, 50, by = 25)
  ) +
  scale_x_continuous(
    breaks = seq(0, 50, by = 25)
  ) +
  theme_bw() +
  theme(
    aspect.ratio = 1,
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(colour = "darkgrey"),
    legend.position = "bottom",
    legend.title = element_blank(),
    rect = element_blank(),
    axis.ticks.length = unit(0, "pt")
  ) 



```

Botanical plot to monitor forest growth. Each triangle represents a tree.
